# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-aad204fb-4f3e-4fa7-b70b-1921b2be9963";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-aad204fb-4f3e-4fa7-b70b-1921b2be9963".device = "/dev/disk/by-uuid/aad204fb-4f3e-4fa7-b70b-1921b2be9963";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B4F3-1A07";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
